version: "3.8"
services:

  okapi:
    container_name: okapi-folio
    build:
      context: ./modules/okapi/okapi-core
      dockerfile: Dockerfile
    ports:
      - 9130:9130
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["dev"]
    environment:
      - JAVA_OPTIONS=-Dloglevel=DEBUG -Dtrace_headers=true -Dstorage=postgres -Dport_end=9199 -Denable_system_auth=true -Dpostgres_host=postgres -Dpostgres_port=5432 -Dpostgres_database=okapi_modules -Dpostgres_username=folio_admin -Dpostgres_password=folio_admin

  postgres:
    container_name: postgres-folio
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=okapi_modules
      - POSTGRES_USER=folio_admin
      - POSTGRES_PASSWORD=folio_admin
      - PGDATA=/data/postgres
      - POSTGRES_SUPERUSER_USERNAME=postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-folio
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
  
  zookeeper:
    restart: always
    container_name: zookeeper-folio
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper-volume:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    restart: always
    container_name: kafka-folio
    image: docker.io/bitnami/kafka:3.3
    ports:
      - "9092:9093"
    volumes:
      - "kafka-volume:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  elasticsearch:
    container_name: elasticsearch-folio
    image: bitnami/elasticsearch:7.17.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - ELASTICSEARCH_PLUGINS=analysis-icu,analysis-kuromoji,analysis-smartcn,analysis-nori,analysis-phonetic
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.0
    container_name: kibana_folio
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
     - 5601:5601
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch_folio:9200
    depends_on:
      - elasticsearch_folio

volumes:
  postgres:
  pgadmin:
  zookeeper-volume:
  kafka-volume:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local
